#Name - of the workflow
name: Build and deploy JAR app to Azure Web App - Carsv1-test1

#on - The event which triggers the code to run
#If someone pushes to the branch called "Week1"
#It's posible to add more brancheh
on:
  push:
    #branches is a list
    branches:
      - week1
      #another branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    #needs - This makes sure that the other job (build) has completed before this job (deploy) can execute
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Carsv1-test1'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8F3FF9571E0B47C296C019D932274401 }}
          package: '*.jar'
